swagger: '2.0'
info:
  version: 1.0.0
  title: Finance and Risk * Market Risk * Limit and Exposure Management
host: 10.17.202.119:8580
basePath: /application/api/limit-exposure-management
tags:
- name: limits
  description: Limits
paths:
  /limits:
    get:
      tags:
      - limits
      summary: Get limits
      operationId: getAllOfLimits
      produces:
      - '*/*'
      parameters:
      - name: page
        in: query
        description: Number of page to retrieve (0..N)
        required: false
        type: integer
        format: int32
      - name: size
        in: query
        description: Number of records per page
        required: false
        type: integer
        format: int32
      - name: sort
        in: query
        description: 'Sorting criteria in the format: attrName,asc|desc. Order is
          optional, default ascending. Multiple sort criteria are supported.'
        required: false
        type: string
      - name: X-Correlation-ID
        in: header
        description: 'Correlation ID (maxLength: 300)'
        required: false
        type: string
      - name: X-Request-ID
        in: header
        description: 'Request ID (maxLength: 300)'
        required: false
        type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/PageOfLimit'
        '400':
          description: Bad Request. Invalid body or parameters of request
          schema:
            $ref: '#/definitions/ProblemResponse'
        '401':
          description: Unauthorized. Request needs authentication
        '404':
          description: Not Found. A resource indicated by URI does not exist in the
            API
          schema:
            $ref: '#/definitions/ProblemResponse'
        '406':
          description: Not Acceptable. A data type unsupported by the resource was
            indicated in the Accept header
        '415':
          description: Unsupported Media Type. A data type unsupported by the resource
            was transferred in the Content-Type header
        '500':
          description: Internal Server Error. Other error (exception) reported by
            the server
          schema:
            $ref: '#/definitions/ProblemResponse'
        '503':
          description: Service Unavailable. The connection with the service is currently
            impossible
      security:
      - oauth2schema:
        - read
        - write
    post:
      tags:
      - limits
      summary: Add new limit
      operationId: addNewOfLimits
      consumes:
      - application/json
      produces:
      - '*/*'
      parameters:
      - in: body
        name: limit
        description: limit
        required: true
        schema:
          $ref: '#/definitions/Limit'
      - name: X-Correlation-ID
        in: header
        description: 'Correlation ID (maxLength: 300)'
        required: false
        type: string
      - name: X-Request-ID
        in: header
        description: 'Request ID (maxLength: 300)'
        required: true
        type: string
      responses:
        '201':
          description: Created. The new resource has been created
          schema:
            $ref: '#/definitions/Limit'
        '400':
          description: Bad Request. Invalid body or parameters of request
          schema:
            $ref: '#/definitions/ProblemResponse'
        '401':
          description: Unauthorized. Request needs authentication
        '404':
          description: Not Found. A resource indicated by URI does not exist in the
            API
          schema:
            $ref: '#/definitions/ProblemResponse'
        '406':
          description: Not Acceptable. A data type unsupported by the resource was
            indicated in the Accept header
        '409':
          description: com.asseco.cb.foundation.api.server.swagger.SwaggerDocketGenerator.CONFLICT_DESC
          schema:
            $ref: '#/definitions/ProblemResponse'
        '412':
          description: Precondition Failed. Object version incompatibility
          schema:
            $ref: '#/definitions/ProblemResponse'
        '415':
          description: Unsupported Media Type. A data type unsupported by the resource
            was transferred in the Content-Type header
        '422':
          description: Unprocessable Entity. One or more constraints have been violated.
            Validation error(s) occur
          schema:
            $ref: '#/definitions/ProblemResponseWithViolations'
        '425':
          description: Too Early. Request repeated while the original one is still
            processed
          schema:
            $ref: '#/definitions/ProblemResponse'
        '500':
          description: Internal Server Error. Other error (exception) reported by
            the server
          schema:
            $ref: '#/definitions/ProblemResponse'
        '503':
          description: Service Unavailable. The connection with the service is currently
            impossible
      security:
      - oauth2schema:
        - read
        - write
  /limits/{id}:
    get:
      tags:
      - limits
      summary: Get limit
      operationId: getOneOfLimits
      produces:
      - '*/*'
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: integer
        format: int64
      - name: X-Correlation-ID
        in: header
        description: 'Correlation ID (maxLength: 300)'
        required: false
        type: string
      - name: X-Request-ID
        in: header
        description: 'Request ID (maxLength: 300)'
        required: false
        type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Limit'
        '400':
          description: Bad Request. Invalid body or parameters of request
          schema:
            $ref: '#/definitions/ProblemResponse'
        '401':
          description: Unauthorized. Request needs authentication
        '404':
          description: Not Found. A resource indicated by URI does not exist in the
            API
          schema:
            $ref: '#/definitions/ProblemResponse'
        '406':
          description: Not Acceptable. A data type unsupported by the resource was
            indicated in the Accept header
        '415':
          description: Unsupported Media Type. A data type unsupported by the resource
            was transferred in the Content-Type header
        '500':
          description: Internal Server Error. Other error (exception) reported by
            the server
          schema:
            $ref: '#/definitions/ProblemResponse'
        '503':
          description: Service Unavailable. The connection with the service is currently
            impossible
      security:
      - oauth2schema:
        - read
        - write
securityDefinitions:
  oauth2schema:
    type: oauth2
    tokenUrl: http://10.17.202.119:8580/application/oauth/token
    flow: application
    scopes:
      read: '''read all'' scope'
      write: '''write all'' scope. Note that server generates ''read write'' as a
        default scope if none is passed'
definitions:
  ConstraintViolation:
    type: object
    properties:
      code:
        type: string
        description: Violation code
      message:
        type: string
        description: Message in the user’s language intended to be displayed to the
          user
      property:
        type: string
        description: Attribute (field) which the validation pertains to (optional
          information, exists only for validations directly connected with fields)
      reference:
        type: string
        description: Object reference
    title: ConstraintViolation
  DatePeriod:
    type: object
    properties:
      from:
        type: string
        format: date
        example: '2000-12-31'
      to:
        type: string
        format: date
        example: '2000-12-31'
    title: DatePeriod
  EntityState:
    type: object
    properties:
      active:
        type: boolean
        readOnly: true
      canceled:
        type: boolean
        readOnly: true
      copy:
        type: boolean
        readOnly: true
      finished:
        type: boolean
        readOnly: true
      forAccept:
        type: boolean
        readOnly: true
      new:
        type: boolean
        readOnly: true
      source:
        type: boolean
        readOnly: true
    title: EntityState
  Limit:
    type: object
    required:
    - amount
    - validityPeriod
    properties:
      _state:
        readOnly: true
        $ref: '#/definitions/EntityState'
      amount:
        description: 'Amount

          Validations: @NotNull'
        $ref: '#/definitions/Money'
      businessUnit:
        type: string
        description: 'Dictionary: BusinessUnitItem (BANK_UNITS)'
      contractId:
        type: integer
        format: int64
        readOnly: true
      customerId:
        type: integer
        format: int64
      entityType:
        type: string
        readOnly: true
      id:
        type: integer
        format: int64
        readOnly: true
      lastChangesDate:
        type: string
        format: date-time
        example: '2000-12-31T23:59:59'
        readOnly: true
      limitType:
        type: string
        description: Limit type
        enum:
        - CREDIT
        - CYCLE
        - DAILY
        - FX
        - FX_SETTLEMENT
        - MONTHLY
        - RENEWABLE
      productId:
        type: integer
        format: int64
      symbol:
        type: string
        readOnly: true
      validityPeriod:
        description: 'Validity period

          Validations: @NotNull'
        $ref: '#/definitions/DatePeriod'
      version:
        type: integer
        format: int32
        readOnly: true
    title: Limit
  Money:
    type: object
    required:
    - amount
    - currency
    properties:
      amount:
        type: number
        description: 'Amount

          Validations: @NotNull'
      currency:
        type: string
        description: 'Validations: @NotNull'
    title: Money
  PageOfLimit:
    type: object
    properties:
      content:
        type: array
        readOnly: true
        items:
          $ref: '#/definitions/Limit'
      empty:
        type: boolean
        readOnly: true
      first:
        type: boolean
        readOnly: true
      last:
        type: boolean
        readOnly: true
      number:
        type: integer
        format: int32
        readOnly: true
      numberOfElements:
        type: integer
        format: int32
        readOnly: true
      pageable:
        readOnly: true
        $ref: '#/definitions/Pageable'
      size:
        type: integer
        format: int32
        readOnly: true
      sort:
        readOnly: true
        $ref: '#/definitions/Sort'
      totalElements:
        type: integer
        format: int64
        readOnly: true
      totalPages:
        type: integer
        format: int32
        readOnly: true
    title: PageOfLimit
  Pageable:
    type: object
    properties:
      offset:
        type: integer
        format: int64
        readOnly: true
      pageNumber:
        type: integer
        format: int32
        readOnly: true
      pageSize:
        type: integer
        format: int32
        readOnly: true
      paged:
        type: boolean
        readOnly: true
      sort:
        readOnly: true
        $ref: '#/definitions/Sort'
      unpaged:
        type: boolean
        readOnly: true
    title: Pageable
  ProblemResponse:
    type: object
    properties:
      description:
        type: string
        description: Wider explanation of the problem
      detail:
        type: string
        description: Details of the error in the form intended for inclusion in the
          log
      instance:
        type: string
        description: Content of X-Request-ID header
      status:
        type: integer
        format: int32
        description: HTTP status
      title:
        type: string
        description: Short description of the problem in the user’s language
      type:
        type: string
        description: Code of the problem
    title: ProblemResponse
  ProblemResponseWithViolations:
    type: object
    properties:
      description:
        type: string
        description: Wider explanation of the problem
      detail:
        type: string
        description: Details of the error in the form intended for inclusion in the
          log
      instance:
        type: string
        description: Content of X-Request-ID header
      status:
        type: integer
        format: int32
        description: HTTP status
      title:
        type: string
        description: Short description of the problem in the user’s language
      type:
        type: string
        description: Code of the problem
      violations:
        type: array
        description: Validation errors
        items:
          $ref: '#/definitions/ConstraintViolation'
    title: ProblemResponseWithViolations
  Sort:
    type: object
    properties:
      empty:
        type: boolean
        readOnly: true
      sorted:
        type: boolean
        readOnly: true
      unsorted:
        type: boolean
        readOnly: true
    title: Sort
